% cuda_path = fullfile('/','usr','local','cuda-6.5');
% blas_path = fullfile('/','home','alexis','OpenBLAS','installation','lib');
% % system('make clean');
% % system('make -j 6');

myArch = computer('arch');
pathToOpts = fullfile(matlabroot,'toolbox','distcomp','gpu','extern','src','mex',myArch,'gcc',['mex_CUDA_' myArch '.xml']);
copyfile(pathToOpts,'.','f')


% mex('-v','-largeArrayDims','matlab/caffe/matcaffe.cu', ...
%     '&quot; -Wl, --whole-archive .build_release/lib/libcaffe.a -Wl,--no-whole-archive &quot;',...
%     ['-I' fullfile(pwd,'.build_release','src')],...
%     ['-I' fullfile(pwd,'include')], ...
%     '-L/usr/local/cuda-6.5/lib64/', ...
%     '-L/usr/local/cuda-6.5/lib/', ...
%     '-L/usr/local/lib', ...
%     '-L/usr/lib', ...
%     '-L/home/alexis/OpenBLAS/installation/lib', ...
%     '-L.build_release/lib','-lcudart','-lcublas','-lcurand','-lglog', ...
%     '-lgflags','-lprotobuf','-lleveldb','-lsnappy','-llmdb','-lhdf5', ...
%     '-lboost_system','-lhdf5_hl','-lm', '-lopencv_core','-lc','-lstdc++',...
%     '-lopencv_imgproc','-lboost_thread','-lcudnn','-lopenblas','-lopencv_highgui',...
%     '-output',fullfile('matlab','caffe','caffe.mexa64'));